// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protoc/include/java/people.proto

package com.example.tutorial;

public interface PeopleOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tutorial.People)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   */
  int getId();

  /**
   * <code>string name = 2;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string email = 300;</code>
   */
  java.lang.String getEmail();
  /**
   * <code>string email = 300;</code>
   */
  com.google.protobuf.ByteString
      getEmailBytes();
}
